# Generated by Django 4.0 on 2021-12-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_product_name_rename_price_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
