# Generated by Django 4.0 on 2021-12-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
